In [39]:
gn = pd.read_csv('26.csv', nrows=50000)

In [40]:
gn1 = gn[['air1','car1']]

In [32]:
fg = gn1.mean()

In [33]:
fg.to_csv('mean.csv')

In [24]:
import glob # use your path
ghj = '*.csv'
allFiles = glob.glob(ghj)
print allFiles
file1 = allFiles
import pandas as pd
data2 = pd.DataFrame()
for i in file1:
    print i
    data = pd.read_csv(i, nrows=90000)
    data1 = pd.DataFrame(data['air1'])
    data2 = pd.concat([data1,data2],axis=1)
data2.to_csv('air.csv')

2641.csv
4447.csv
2974.csv
3224.csv
2787.csv
3192.csv
3531.csv
2814.csv
2004.csv
4302.csv
3036.csv
4313.csv
2233.csv
1782.csv
3723.csv
4767.csv
4298.csv
3652.csv
2769.csv
4874.csv
2575.csv
2953.csv
160.csv
370.csv
26.csv
3367.csv
4193.csv
1718.csv
2864.csv
2199.csv
3504.csv
3795.csv
2158.csv
2755.csv
1800.csv
1283.csv
1632.csv
3500.csv
2156.csv
1681.csv

In [147]:
da1 = pd.read_csv('dryer.csv')

In [148]:
da3 = da1.fillna(0)

In [149]:
da2 = da3.transpose()

In [150]:
da4 = da2.iloc[1:]

In [123]:
da5 = da4.transpose()

In [124]:
da6 = da5.mean(axis=1)

In [125]:
da6.to_csv('dryerproj.csv')

In [151]:
from sklearn.cluster import KMeans
k_mea= KMeans(init='k-means++', n_clusters=4)
barc = k_mea.fit(da4)
fdf2 = pd.DataFrame(barc.cluster_centers_)

In [152]:
fdf3 = fdf2.transpose()

In [153]:
fdf3

               0      1  2  3
0       0.108383  0.003  0  0
1       0.082280  0.000  0  0
2       0.069019  0.000  0  0
3       0.090336  0.000  0  0
4       0.111140  0.000  0  0
5       0.088589  0.004  0  0
6       0.092495  0.004  0  0
7       0.144178  0.004  0  0
8       0.088972  0.004  0  0
9       0.063374  0.000  0  0
10      0.095523  0.000  0  0
11      0.110757  0.000  0  0
12      0.073533  0.000  0  0
13      0.092570  0.000  0  0
14      0.068579  0.000  0  0
15      0.079766  0.004  0  0
16      0.059570  0.004  0  0
17      0.113252  0.004  0  0
18      0.057944  0.004  0  0
19      0.051617  0.004  0  0
20      0.048794  0.000  0  0
21      0.056832  0.000  0  0
22      0.058682  0.000  0  0
23      0.032654  0.000  0  0
24      0.068776  0.000  0  0
25      0.027075  0.000  0  0
26      0.056991  0.000  0  0
27      0.037467  0.000  0  0
28      0.046654  0.003  0  0
29      0.046617  0.000  0  0
...          ...    ... .. ..
499970  0.031607  0.402  0  0
499971  0.058505  0.404  0  0
499972  0.080009  0.405  0  0
499973  0.053664  2.582  0  0
499974  0.020645  0.408  0  0
499975  0.021579  0.407  0  0
499976  0.028150  0.410  0  0
499977  0.019056  0.407  0  0
499978  0.016551  0.408  0  0
499979  0.028617  0.410  0  0
499980  0.009589  0.412  0  0
499981  0.043290  0.411  0  0
499982  0.032822  0.413  0  0
499983  0.011449  0.412  0  0
499984  0.020907  0.412  0  0
499985  0.016458  0.408  0  0
499986  0.024710  0.409  0  0
499987  0.010028  0.411  0  0
499988  0.025355  0.412  0  0
499989  0.007654  0.414  0  0
499990  0.026888  0.417  0  0
499991  0.003047  0.419  0  0
499992  0.026346  0.418  0  0
499993  0.002748  0.419  0  0
499994  0.013701  0.421  0  0
499995  0.013682  0.422  0  0
499996  0.017206  0.422  0  0
499997  0.049813  0.424  0  0
499998  0.052178  0.423  0  0
499999  0.051841  0.424  0  0

[500000 rows x 4 columns]

In [154]:
 fdf3.to_csv('dryer5.csv')